name: smartcook_cor
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  url_launcher: ^6.2.1
  firebase_core: 2.21.0
  cloud_firestore: 4.12.2
  firebase_auth: ^4.12.1
  google_sign_in: ^6.1.5
  flutter_launcher_icons: ^0.13.1
  shared_preferences: ^2.2.2
  flutter_native_splash: ^2.3.5
  flutter_svg: ^2.0.9
  logger: ^2.0.2+1
  flutter_easyloading: ^3.0.5
  google_nav_bar: ^5.0.6
  line_icons: ^2.0.3
  fl_chart: ^0.64.0
  youtube_player_flutter: ^8.1.2
  flutter_inappwebview: ^5.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "asset/icons/icon.png"
flutter_native_splash:
  android: true
  ios: true
  web: false
  background_image: "asset/splash.png" 

flutter:
  uses-material-design: true
  assets:
    - asset/svg/GoogleIcons.svg
