// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCVGXrtH3jLihFfyDHdPhEtZSPAF06F_5Y',
    appId: '1:1084781215303:web:3cda3e5bbbd24769c0bb62',
    messagingSenderId: '1084781215303',
    projectId: 'smartcook-cor',
    authDomain: 'smartcook-cor.firebaseapp.com',
    storageBucket: 'smartcook-cor.appspot.com',
    measurementId: 'G-XX46JBDDJH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCe6NDKaD5xCDt1pWqrS0eHzUHkTK5nDXs',
    appId: '1:1084781215303:android:e54fa3cc69c055ebc0bb62',
    messagingSenderId: '1084781215303',
    projectId: 'smartcook-cor',
    storageBucket: 'smartcook-cor.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDShM_c_HAZn0ize9fqyoKOS4YmXEwaIN0',
    appId: '1:1084781215303:ios:684870331e95255dc0bb62',
    messagingSenderId: '1084781215303',
    projectId: 'smartcook-cor',
    storageBucket: 'smartcook-cor.appspot.com',
    androidClientId: '1084781215303-puqqohtsn7s1he1l9sh260p090lpi6pr.apps.googleusercontent.com',
    iosClientId: '1084781215303-1nqqmsl4hf6c0q6t7vb0hjnn33r2b44u.apps.googleusercontent.com',
    iosBundleId: 'com.example.smartcookCor',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDShM_c_HAZn0ize9fqyoKOS4YmXEwaIN0',
    appId: '1:1084781215303:ios:dc73f7a17419de3ac0bb62',
    messagingSenderId: '1084781215303',
    projectId: 'smartcook-cor',
    storageBucket: 'smartcook-cor.appspot.com',
    androidClientId: '1084781215303-puqqohtsn7s1he1l9sh260p090lpi6pr.apps.googleusercontent.com',
    iosClientId: '1084781215303-ijdpe9mm8e3iva8mfbbeos738f6683a3.apps.googleusercontent.com',
    iosBundleId: 'com.example.smartcookCor.RunnerTests',
  );
}
